### ISSUE TITLE
Storage Buckets

### ISSUE THREAD

**Issue by jaikishantulswani** [bayotop/off-by-slash#2]
It could be much more useful if you update the regex to find storage buckets too like Amazon, DigitalOcean,googleapis.com & windows.net

**Comment by bayotop** [comment]
I'm not seeing the advantage in doing that. Could you please clarify why you want me to include those services?

I intended scrape.py to generate a list of resources on targeted domains. Running the off-by-slash active scan doesn't make sense with resources hosted on third-party services (presuming you wish to stay in-scope in respect to the URLs passed to scrape.py).

**Comment by jaikishantulswani** [comment]
Hello @bayotop ,
I am using this apart from burp suite to scrap all the links as well as storage buckets from provided list of hosts.

**Comment by bayotop** [comment]
In that case you need to modify the file to fit your needs. You should modify lines 56 to 58 were the filtering is happening. 

I'll close this issue now, as these changes won't be added within this project.

**Comment by jaikishantulswani** [comment]
Hello @bayotop ,
Could you please share the updated regex here which include the scraping of storage buckets too.
Thank you.

**Comment by bayotop** [comment]
The regex is really not the issue, it will also match storage buckets. I subsequently filter out the results on lines 56-58 as I already mentioned.
